### ISSUE TITLE
Current issue with the Construct

### ISSUE THREAD

**Issue by Noxxis90** [Moocowsgomoo/StS-ConstructMod#13]
While playing the mod I have encountered a game crashing bug that most likely occures when something attempts to put cards in draw pile. Mega-upgraded panic fire, master core, replicate and similar effects that attempt to put a card/s in draw pile cause game to crash entirely.

**Comment by Moocowsgomoo** [comment]
Make sure you've downloaded the latest version of the [Construct](https://github.com/Moocowsgomoo/StS-ConstructMod/releases), [ModTheSpire](https://github.com/kiooeht/ModTheSpire/releases), and [BaseMod](https://github.com/daviscook477/BaseMod/releases) - this behaviour should have been fixed in a previous release. Let me know if the problem still occurs with the most recent versions. Thanks!
